import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    final localizations =
        Localizations.of<AppLocalizations>(context, AppLocalizations);
    if (localizations == null) {
      return AppLocalizations(const Locale('en'));
    }
    return localizations;
  }

  String get(String key) {
    final localizedMap = _localizedValues[locale.languageCode];
    final fallbackMap = _localizedValues['en'];

    if (localizedMap != null && localizedMap.containsKey(key)) {
      return localizedMap[key]!;
    } else if (fallbackMap != null && fallbackMap.containsKey(key)) {
      return fallbackMap[key]!;
    } else {
      return key; // Optionally return key itself if missing in all
    }
  }

  static const _localizedValues = {
    'en': {
      // Common
      'app_name': 'Expense Tracker',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'error': 'Error',
      'success': 'Success',
      'loading': 'Loading...',
      'retry': 'Retry',
      'confirm': 'Confirm',
      'back': 'Back',
      'next': 'Next',
      'done': 'Done',
      'search': 'Search',
      'filter': 'Filter',
      'sort': 'Sort',
      'no_data': 'No data available',
      'no_internet': 'No internet connection',
      'try_again': 'Please try again',
      'there': 'there',
      'add_first_transaction': 'Add your first transaction',

      // Greetings
      'good_morning': 'Good Morning',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',

      // Home Page
      'financial_overview': 'Here\'s your financial overview',
      'total_balance': 'Total Balance',
      'income': 'Income',
      'expenses': 'Expenses',
      'savings': 'Savings',
      'recent_transactions': 'Recent Transactions',
      'no_transactions': 'No transactions yet',
      'monthly_trend': 'Monthly Trend',
      'income_trend': 'Income Trend',
      'expense_trend': 'Expense Trend',
      'savings_trend': 'Savings Trend',
      'this_month': 'This Month',
      'last_month': 'Last Month',
      'trend_up': 'Trending Up',
      'trend_down': 'Trending Down',
      'trend_stable': 'Stable',
      'percentage_change': '{percentage}% {direction} from last month',

      // Auth
      'login': 'Login',
      'register': 'Register',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': 'Don\'t have an account?',
      'already_have_account': 'Already have an account?',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'sign_out': 'Sign Out',
      'guest_mode': 'Continue as Guest',
      'remember_me': 'Remember Me',
      'reset_password': 'Reset Password',
      'password_reset_sent': 'Password reset email sent',
      'password_reset_sent_message':
          'Password reset instructions have been sent to your email. Please check your inbox and follow the instructions.',
      'password_reset_success': 'Password reset successful',
      'password_reset_error': 'Failed to reset password',
      'invalid_email': 'Invalid email address',
      'invalid_password': 'Password must be at least 6 characters',
      'passwords_dont_match': 'Passwords do not match',
      'login_error': 'Invalid email or password',
      'register_error': 'Failed to create account',
      'email_in_use': 'Email already in use',
      'enter_email': 'Enter your email',
      'enter_password': 'Enter your password',
      'enter_confirm_password': 'Confirm your password',
      'email_required': 'Please enter your email',
      'password_required': 'Please enter your password',
      'confirm_password_required': 'Please confirm your password',
      'first_name_required': 'Please enter your first name',
      'last_name_required': 'Please enter your last name',
      'accept_terms': 'I accept the Terms and Conditions',
      'open_email_app': 'Open Email App',
      'send_reset_link': 'Send Reset Link',
      'forgot_password_message':
          'Enter your email address and we\'ll send you a link to reset your password.',

      // Profile
      'profile': 'Profile',
      'language': 'Language',
      'currency': 'Currency',
      'settings': 'Settings',
      'logout': 'Logout',
      'edit_profile': 'Edit Profile',
      'change_password': 'Change Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'profile_picture': 'Profile Picture',
      'take_photo': 'Take Photo',
      'choose_photo': 'Choose from Gallery',
      'remove_photo': 'Remove Photo',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'phone': 'Phone Number',
      'address': 'Address',
      'bio': 'Bio',
      'notifications': 'Notifications',
      'dark_mode': 'Dark Mode',
      'system_theme': 'System Theme',
      'light_theme': 'Light Theme',
      'dark_theme': 'Dark Theme',

      // Expenses
      'expense_type': 'Expense',
      'income_type': 'Income',
      'transfer': 'Transfer',
      'recurring': 'Recurring',
      'one_time': 'One Time',
      'daily': 'Daily',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'frequency': 'Frequency',
      'total_expenses': 'Total Expenses',
      'total_income': 'Total Income',
      'net_balance': 'Net Balance',

      // Categories
      'food': 'Food',
      'transport': 'Transport',
      'shopping': 'Shopping',
      'bills': 'Bills',
      'entertainment': 'Entertainment',
      'health': 'Health',
      'education': 'Education',
      'other': 'Other',
      'add_category': 'Add Category',
      'edit_category': 'Edit Category',
      'delete_category': 'Delete Category',
      'category_name': 'Category Name',
      'enter_category_name': 'Enter category name',
      'category_name_required': 'Please enter a category name',
      'delete_category_confirmation': 'Are you sure you want to delete {name}?',
      'budget': 'Budget',
      'enter_budget': 'Enter budget amount',
      'description': 'Description',

      // Messages
      'profile_updated': 'Profile updated successfully',
      'language_updated': 'Language updated successfully',
      'currency_updated': 'Currency updated successfully',
      'expense_added': 'Expense added successfully',
      'income_added': 'Income added successfully',
      'transaction_deleted': 'Transaction deleted successfully',
      'category_added': 'Category added successfully',
      'category_updated': 'Category updated successfully',
      'category_deleted': 'Category deleted successfully',
      'password_changed': 'Password changed successfully',
      'settings_updated': 'Settings updated successfully',
      'changes_saved': 'Changes saved successfully',
      'error_occurred': 'An error occurred',
      'try_again_later': 'Please try again later',
      'operation_failed': 'Operation failed',
      'network_error': 'Network error',
      'server_error': 'Server error',
      'validation_error': 'Please check your input',
      'required_field': 'This field is required',
      'invalid_input': 'Invalid input',
      'success_message': 'Operation completed successfully',

      // Profile Page
      'account_settings': 'Account Settings',
      'preferences': 'Preferences',
      'appearance': 'Appearance',
      'logout_confirmation': 'Are you sure you want to logout?',

      // Currency Names
      'currency_birr': 'Ethiopian Birr',
      'currency_usd': 'US Dollar',
      'currency_eur': 'Euro',
      'currency_gbp': 'British Pound',
      'currency_jpy': 'Japanese Yen',
      'currency_inr': 'Indian Rupee',
      'currency_cny': 'Chinese Yuan',
      'close': 'Close',

      // Edit Profile Dialog
      'image_pick_error': 'Failed to pick image',
      'profile_update_error': 'Error updating profile:',
      'dismiss': 'Dismiss',

      // Category Errors
      'category_id_required': 'Category ID is required',
      'category_not_found': 'Category not found',
      'cannot_update_default': 'Cannot update default categories',
      'cannot_delete_default': 'Cannot delete default categories',
      'server_failure': 'Server failure',
      'cache_failure': 'Cache failure',
      'unexpected_error': 'Unexpected error',

      // Category Remote Data Source Errors
      'failed_to_save_category': 'Failed to save category',
      'failed_to_get_category': 'Failed to get category',
      'failed_to_get_categories': 'Failed to get categories',
      'failed_to_update_category': 'Failed to update category',
      'failed_to_delete_category': 'Failed to delete category',
      'failed_to_get_categories_by_type': 'Failed to get categories by type',

      // Category Repository Errors
      'no_internet_connection': 'No internet connection',
      'category_not_found_cache': 'Category not found in local storage',
      'failed_to_cache_category': 'Failed to cache category',
      'failed_to_cache_categories': 'Failed to cache categories',
      'failed_to_get_remote_category': 'Failed to get remote category',
      'failed_to_add_remote_category': 'Failed to add remote category',
      'failed_to_update_remote_category': 'Failed to update remote category',

      // Add Transaction Page
      'add_transaction': 'Add Transaction',
      'title': 'Title',
      'enter_amount': 'Enter Amount',
      'select_category': 'Select Category',
      'no_categories': 'No categories available',
      'date': 'Date',
      'time': 'Time',
      'no_description': 'No description',

      // Edit Transaction Page
      'edit_transaction': 'Edit Transaction',
      'update_transaction': 'Update Transaction',
      'delete_transaction': 'Delete Transaction',
      'delete_transaction_confirmation':
          'Are you sure you want to delete this transaction?',
      'transaction_updated': 'Transaction updated successfully',
      'transaction_delete_error': 'Failed to delete transaction',
    },
    'am': {
      // Common
      'app_name': 'የወጪ መከታተል',
      'cancel': 'ሰርዝ',
      'save': 'አስቀምጥ',
      'delete': 'ሰርዝ',
      'edit': 'አርትዕ',
      'error': 'ስህተት',
      'success': 'ተሳክቷል',
      'loading': 'በመጫን ላይ...',
      'retry': 'እንደገና ይሞከሩ',
      'confirm': 'አረጋግጥ',
      'back': 'ተመለስ',
      'next': 'ቀጣይ',
      'done': 'ተጠናቅቋል',
      'search': 'ፈልግ',
      'filter': 'አጣራ',
      'sort': 'ያዝዝ',
      'no_data': 'ዳሰሳ የለም',
      'no_internet': 'የኢንተርኔት ግንኙነት የለም',
      'try_again': 'እባክዎ እንደገና ይሞከሩ',
      'there': 'እዚያ',
      'add_first_transaction': 'የመጀመሪያዎን ግብይት ያክሉ',

      // Greetings
      'good_morning': 'እንደምን አደሩ',
      'good_afternoon': 'እንደምን አረፈዱ',
      'good_evening': 'እንደምን አመሹ',

      // Home Page
      'financial_overview': 'የገንዘብ አጠቃላይ እይታዎ',
      'total_balance': 'ጠቅላላ ቀሪ',
      'income': 'ገቢ',
      'expenses': 'ወጪዎች',
      'savings': 'ቁጠባ',
      'recent_transactions': 'የቅርብ ጊዜ ግብይቶች',
      'no_transactions': 'እስካሁን ምንም ግብይት የለም',
      'monthly_trend': 'ወርሃዊ አዝማሚያ',
      'income_trend': 'የገቢ አዝማሚያ',
      'expense_trend': 'የወጪ አዝማሚያ',
      'savings_trend': 'የቁጠባ አዝማሚያ',
      'this_month': 'ይህ ወር',
      'last_month': 'ባለፈው ወር',
      'trend_up': 'እየጨመረ ነው',
      'trend_down': 'እየቀነሰ ነው',
      'trend_stable': 'ቋሚ ነው',
      'percentage_change': 'ከባለፈው ወር {percentage}% {direction}',

      // Auth
      'login': 'ግባ',
      'register': 'ይመዝገቡ',
      'email': 'ኢሜይል',
      'password': 'የይለፍ ቃል',
      'confirm_password': 'የይለፍ ቃል አረጋግጥ',
      'forgot_password': 'የይለፍ ቃልዎን ረሱ?',
      'dont_have_account': 'መለያ የላችሁም?',
      'already_have_account': 'አስቀድመው መለያ አላችሁ?',
      'sign_in': 'ግባ',
      'sign_up': 'ይመዝገቡ',
      'sign_out': 'ውጣ',
      'guest_mode': 'እንደ እንግድ ይቀጥሉ',
      'remember_me': 'አስታውሰኝ',
      'reset_password': 'የይለፍ ቃል ዳግም ያዘጋጁ',
      'password_reset_sent': 'የይለፍ ቃል ዳግም የማዘጋጃ ኢሜይል ተልኳል',
      'password_reset_sent_message':
          'የይለፍ ቃል ዳግም የማዘጋጃ መመሪያዎች ወደ ኢሜይልዎ ተልከዋል። እባክዎ የገቢ ሳጥንዎን ያረጋግጡ እና መመሪያዎቹን ይከተሉ።',
      'password_reset_success': 'የይለፍ ቃል በተሳክቶ ተዘጋጅቷል',
      'password_reset_error': 'የይለፍ ቃል እንደገና ማዘጋጀት አልተሳካም',
      'invalid_email': 'ልክ ያልሆነ ኢሜይል አድራሻ',
      'invalid_password': 'የይለፍ ቃል ቢያንስ 6 ቁምፊ መሆን አለበት',
      'passwords_dont_match': 'የይለፍ ቃሎች አይጣጣሙም',
      'login_error': 'ልክ ያልሆነ ኢሜይል ወይም የይለፍ ቃል',
      'register_error': 'መለያ መፍጠር አልተሳካም',
      'email_in_use': 'ኢሜይል አስቀድሞ ተጠቅሟል',
      'enter_email': 'ኢሜይልዎን ያስገቡ',
      'enter_password': 'የይለፍ ቃልዎን ያስገቡ',
      'enter_confirm_password': 'የይለፍ ቃልዎን ያረጋግጡ',
      'email_required': 'እባክዎ ኢሜይልዎን ያስገቡ',
      'password_required': 'እባክዎ የይለፍ ቃልዎን ያስገቡ',
      'confirm_password_required': 'እባክዎ የይለፍ ቃልዎን ያረጋግጡ',
      'first_name_required': 'እባክዎ የመጀመሪያ ስምዎን ያስገቡ',
      'last_name_required': 'እባክዎ የአያት ስምዎን ያስገቡ',
      'accept_terms': 'የአገልግሎት ውሎችን እቀበላለሁ',
      'open_email_app': 'ኢሜይል መተግበሪያ ክፈት',
      'send_reset_link': 'ዳግም የማዘጋጃ አገናኝ ይላኩ',
      'forgot_password_message':
          'ኢሜይል አድራሻዎን ያስገቡ እና የይለፍ ቃልዎን ለማዘጋጀት አገናኝ እንልካለን።',

      // Profile
      'profile': 'መገለጫ',
      'language': 'ቋንቋ',
      'currency': 'ምንዛሪ',
      'settings': 'ቅንብሮች',
      'logout': 'ውጣ',
      'edit_profile': 'መገለጫ አርትዕ',
      'change_password': 'የይለፍ ቃል ቀይር',
      'current_password': 'አሁን ያለው የይለፍ ቃል',
      'new_password': 'አዲስ የይለፍ ቃል',
      'confirm_new_password': 'አዲሱን የይለፍ ቃል አረጋግጥ',
      'profile_picture': 'የመገለጫ ስዕል',
      'take_photo': 'ስዕል ይውሰዱ',
      'choose_photo': 'ከጋሌሪ ይምረጡ',
      'remove_photo': 'ስዕሉን ያስወግዱ',
      'first_name': 'የመጀመሪያ ስም',
      'last_name': 'የአያት ስም',
      'phone': 'ስልክ ቁጥር',
      'address': 'አድራሻ',
      'bio': 'ታሪክ',
      'notifications': 'ማስታወቂያዎች',
      'dark_mode': 'ጨለማ ሁኔታ',
      'system_theme': 'የስርዓት ገጽታ',
      'light_theme': 'ብርሃን ገጽታ',
      'dark_theme': 'ጨለማ ገጽታ',

      // Expenses
      'expense_type': 'ወጪ',
      'income_type': 'ገቢ',
      'transfer': 'ማዛወር',
      'recurring': 'የሚደገም',
      'one_time': 'አንድ ጊዜ',
      'daily': 'በየቀኑ',
      'weekly': 'በየሳምንቱ',
      'monthly': 'በየወሩ',
      'yearly': 'በየአመቱ',
      'start_date': 'የመጀመሪያ ቀን',
      'end_date': 'የመጨረሻ ቀን',
      'frequency': 'ድግግሞሽ',
      'total_expenses': 'ጠቅላላ ወጪዎች',
      'total_income': 'ጠቅላላ ገቢ',
      'net_balance': 'የተጣራ ቀሪ',

      // Categories
      'food': 'ምግብ',
      'transport': 'መጓጓዣ',
      'shopping': 'ግዢ',
      'bills': 'ሂሳቦች',
      'entertainment': 'አዝናኝ',
      'health': 'ጤና',
      'education': 'ትምህርት',
      'other': 'ሌላ',
      'add_category': 'ምድብ አክል',
      'edit_category': 'ምድብ አርትዕ',
      'delete_category': 'ምድብ ሰርዝ',
      'category_name': 'የምድብ ስም',
      'enter_category_name': 'የምድብ ስም ያስገቡ',
      'category_name_required': 'እባክዎ የምድብ ስም ያስገቡ',
      'delete_category_confirmation': 'እርግጠኛ ነዎት {name} ን መሰረዝ እንደሚፈልጉ?',
      'budget': 'በጀት',
      'enter_budget': 'የበጀት መጠን ያስገቡ',
      'description': 'መግለጫ',

      // Messages
      'profile_updated': 'መገለጫዎ በተሳክቶ ተዘምኗል',
      'language_updated': 'ቋንቋዎ በተሳክቶ ተዘምኗል',
      'currency_updated': 'ምንዛሪዎ በተሳክቶ ተዘምኗል',
      'expense_added': 'ወጪዎ በተሳክቶ ተጨምሯል',
      'income_added': 'ገቢዎ በተሳክቶ ተጨምሯል',
      'transaction_deleted': 'ግብይቱ በተሳክቶ ተሰርዟል',
      'category_added': 'ምድቡ በተሳክቶ ተጨምሯል',
      'category_updated': 'ምድቡ በተሳክቶ ተዘምኗል',
      'category_deleted': 'ምድቡ በተሳክቶ ተሰርዟል',
      'password_changed': 'የይለፍ ቃልዎ በተሳክቶ ተቀይሯል',
      'settings_updated': 'ቅንብሮችዎ በተሳክቶ ተዘምነዋል',
      'changes_saved': 'ለውጦች በተሳክቶ ተቀምጠዋል',
      'error_occurred': 'ስህተት ተከስቷል',
      'try_again_later': 'እባክዎ በኋላ እንደገና ይሞከሩ',
      'operation_failed': 'ክወናው አልተሳካም',
      'network_error': 'የኔትወርክ ስህተት',
      'server_error': 'የሰርቨር ስህተት',
      'validation_error': 'እባክዎ ግብዣዎን ያረጋግጡ',
      'required_field': 'ይህ መስክ ያስፈልጋል',
      'invalid_input': 'ልክ ያልሆነ ግብዣ',
      'success_message': 'ክወናው በተሳክቶ ተጠናቅቋል',

      // Profile Page
      'account_settings': 'የመለያ ቅንብሮች',
      'preferences': 'ምርጫዎች',
      'appearance': 'መልክ',
      'logout_confirmation': 'ውጣ እንደሚፈልጉ እርግጠኛ ነዎት?',

      // Currency Names
      'currency_birr': 'ኢትዮጵያ ብር',
      'currency_usd': 'አሜሪካ ዶላር',
      'currency_eur': 'ዩሮ',
      'currency_gbp': 'የእንግሊዝ ፓውንድ',
      'currency_jpy': 'የጃፓን የን',
      'currency_inr': 'የህንድ ሩፒ',
      'currency_cny': 'የቻይና ዩዋን',
      'close': 'ዝጋ',

      // Edit Profile Dialog
      'image_pick_error': 'ስዕል መምረጥ አልተሳካም',
      'profile_update_error': 'መገለጫ ማዘምን ስህተት:',
      'dismiss': 'ዝጋ',

      // Category Errors
      'category_id_required': 'የምድብ መታወቂያ ያስፈልጋል',
      'category_not_found': 'ምድቡ አልተገኘም',
      'cannot_update_default': 'ነባር ምድብን ማዘምን አይቻልም',
      'cannot_delete_default': 'ነባር ምድብን ማስረዝ አይቻልም',
      'server_failure': 'የሰርቨር ስህተት',
      'cache_failure': 'የኬሽ ስህተት',
      'unexpected_error': 'ያልተጠበቀ ስህተት',

      // Category Remote Data Source Errors
      'failed_to_save_category': 'ምድቡን መቀመጥ አልተሳካም',
      'failed_to_get_category': 'ምድቡን መውሰድ አልተሳካም',
      'failed_to_get_categories': 'ምድቦችን መውሰድ አልተሳካም',
      'failed_to_update_category': 'ምድቡን ማዘምን አልተሳካም',
      'failed_to_delete_category': 'ምድቡን ማስረዝ አልተሳካም',
      'failed_to_get_categories_by_type': 'በዓይነት ምድቦችን መውሰድ አልተሳካም',

      // Add Transaction Page
      'add_transaction': 'ግብይት አክል',
      'title': 'ርዕስ',
      'enter_amount': 'መጠን ያስገቡ',
      'select_category': 'ምድብ ይምረጡ',
      'no_categories': 'ምድቦች አልተገኙም',
      'date': 'ቀን',
      'time': 'ሰዓት',
      'no_description': 'መግለጫ የለም',

      // Edit Transaction Page
      'edit_transaction': 'ግብይት አርትዕ',
      'update_transaction': 'ግብይት አዘምን',
      'delete_transaction': 'ግብይት ሰርዝ',
      'delete_transaction_confirmation': 'ይህን ግብይት መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት?',
      'transaction_update_error': 'ግብይቱን ማዘምን አልተሳካም',
      'transaction_delete_error': 'ግብይቱን ማሰረዝ አልተሳካም',
    },
    'om': {
      // Common
      'app_name': 'Baa\'insa Qabeenyaa',
      'cancel': 'Dhiisi',
      'save': 'Olkaa\'i',
      'delete': 'Haquu',
      'edit': 'Jijjiiruu',
      'error': 'Dogoggora',
      'success': 'Milkaa\'e',
      'loading': 'Fe\'aa jira...',
      'retry': 'Irra deebi\'i',
      'confirm': 'Mirkaneessa',
      'back': 'Deebi\'i',
      'next': 'Itti aanaa',
      'done': 'Xumura',
      'search': 'Barbaadi',
      'filter': 'Seensa',
      'sort': 'Qubeessa',
      'no_data': 'Odeeffannoo hin jiru',
      'no_internet': 'Internet hin jiru',
      'try_again': 'Mee irra deebi\'i',
      'there': 'asii',
      'add_first_transaction': 'Fe\'aa Keessan Duraa Dabalchi',

      // Greetings
      'good_morning': 'Baga Bariin Dhuftan',
      'good_afternoon': 'Baga Guyyaa Dhuftan',
      'good_evening': 'Baga Galgala Dhuftan',

      // Home Page
      'financial_overview': 'Qabeenya Keessan Ibsa',
      'total_balance': 'Waliigala Qabeenya',
      'income': 'Argama',
      'expenses': 'Baa\'insa',
      'savings': 'Qabeenya',
      'recent_transactions': 'Fe\'aa Duraa',
      'no_transactions': 'Fe\'aa Hin Jiru',
      'monthly_trend': 'Ji\'a Ji\'aa Jijjiirama',
      'income_trend': 'Argama Jijjiirama',
      'expense_trend': 'Baa\'insa Jijjiirama',
      'savings_trend': 'Qabeenya Jijjiirama',
      'this_month': 'Ji\'a Kana',
      'last_month': 'Ji\'a Duraa',
      'trend_up': 'Ol\'aanaa Jira',
      'trend_down': 'Gadii Jira',
      'trend_stable': 'Qindaa\'e',
      'percentage_change': 'Ji\'a Duraa irraa {percentage}% {direction}',

      // Auth
      'login': 'Seeni',
      'register': 'Galmaa\'i',
      'email': 'Imeelii',
      'password': 'Jecha Iccitii',
      'confirm_password': 'Jecha Iccitii Mirkaneessa',
      'forgot_password': 'Jecha Iccitii Keessan Dagattanii?',
      'dont_have_account': 'Herrega Hin Qabduu?',
      'already_have_account': 'Herrega Duraa Qabduu?',
      'sign_in': 'Seeni',
      'sign_up': 'Galmaa\'i',
      'sign_out': 'Ba\'i',
      'guest_mode': 'Keessatti Itti Fufe',
      'remember_me': 'Na Yaadadhu',
      'reset_password': 'Jecha Iccitii Irra Deebi\'i',
      'password_reset_sent': 'Imeelii Jecha Iccitii Irra Deebi\'i Ergame',
      'password_reset_sent_message':
          'Jecha Iccitii Irra Deebi\'uu Immeelii Keessan Ergame. Mee Imeelii Keessan Mirkaneessaafi Tilmaama Hordofaa.',
      'password_reset_success': 'Jecha Iccitii Milkaa\'e',
      'password_reset_error': 'Jecha Iccitii Irra Deebi\'uu Hin Dandeenye',
      'invalid_email': 'Imeelii Dogoggora',
      'invalid_password': 'Jecha Iccitii Guutuu 6 Qubee Qabaachuu Qaba',
      'passwords_dont_match': 'Jecha Iccitii Wal Hin Qabatan',
      'login_error': 'Imeelii Ykn Jecha Iccitii Dogoggora',
      'register_error': 'Herrega Uumuu Hin Dandeenye',
      'email_in_use': 'Imeelii Duraan Itti Fayyadamaa Jira',
      'enter_email': 'Imeelii Keessan Galchi',
      'enter_password': 'Jecha Iccitii Keessan Galchi',
      'enter_confirm_password': 'Jecha Iccitii Keessan Mirkaneessa',
      'email_required': 'Mee Imeelii Keessan Galchi',
      'password_required': 'Mee Jecha Iccitii Keessan Galchi',
      'confirm_password_required': 'Mee Jecha Iccitii Keessan Mirkaneessa',
      'first_name_required': 'Mee Maqaa Dhalataa Keessan Galchi',
      'last_name_required': 'Mee Maqaa Abbaa Keessan Galchi',
      'accept_terms': 'Haala Tajaajilaa Fudhaa',
      'open_email_app': 'App Imeelii Bani',
      'send_reset_link': 'Link Irra Deebi\'uu Ergaa',
      'forgot_password_message':
          'Imeelii Keessan Galchaa, Jecha Iccitii Keessan Irra Deebi\'uu Link Erganna.',

      // Profile
      'profile': 'Seenaa',
      'language': 'Afaan',
      'currency': 'Qarshii',
      'settings': 'Qindaawwan',
      'logout': 'Ba\'i',
      'edit_profile': 'Seenaa Jijjiiruu',
      'change_password': 'Jecha Iccitii Jijjiiruu',
      'current_password': 'Jecha Iccitii Ammaa',
      'new_password': 'Jecha Iccitii Haaraa',
      'confirm_new_password': 'Jecha Iccitii Haaraa Mirkaneessa',
      'profile_picture': 'Suuraa Seenaa',
      'take_photo': 'Suuraa Fakkadhu',
      'choose_photo': 'Galeerii Irraa Filadhu',
      'remove_photo': 'Suuraa Qaqqabsi',
      'first_name': 'Maqaa Dhalataa',
      'last_name': 'Maqaa Abbaa',
      'phone': 'Lakkoofsa Bilbilaa',
      'address': 'Teessoo',
      'bio': 'Seenaa',
      'notifications': 'Beekumsa',
      'dark_mode': 'Gara Garaa',
      'system_theme': 'Qaama Sirnii',
      'light_theme': 'Qaama Ifaa',
      'dark_theme': 'Qaama Garaa',

      // Expenses
      'expense_type': 'Baa\'insa',
      'income_type': 'Argama',
      'transfer': 'Dhiibbaa',
      'recurring': 'Irra Deebi\'u',
      'one_time': 'Tokko',
      'daily': 'Guyyaa Guyyaa',
      'weekly': 'Torbee Torbee',
      'monthly': 'Ji\'a Ji\'a',
      'yearly': 'Waggaa Waggaa',
      'start_date': 'Guyyaa Jalqabaa',
      'end_date': 'Guyyaa Xumuraa',
      'frequency': 'Irra Deebi\'uu',
      'total_expenses': 'Waliigala Baa\'insa',
      'total_income': 'Waliigala Argama',
      'net_balance': 'Qabeenya Sirrii',

      // Categories
      'food': 'Nyaata',
      'transport': 'Imala',
      'shopping': 'Bitaa',
      'bills': 'Bilii',
      'entertainment': 'Boqonnaa',
      'health': 'Fayyaa',
      'education': 'Barumsa',
      'other': 'Kaan',
      'add_category': 'Garee Dabalchi',
      'edit_category': 'Garee Jijjiiruu',
      'delete_category': 'Garee Qaqqabsi',
      'category_name': 'Maqaa Garee',
      'enter_category_name': 'Maqaa Garee Galchi',
      'category_name_required': 'Mee Maqaa Garee Galchi',
      'delete_category_confirmation': 'Mee {name} Haquu Barbaaddanii?',
      'budget': 'Bajeta',
      'enter_budget': 'Lakki Bajetaa Galchi',
      'description': 'Ibsa',

      // Messages
      'profile_updated': 'Seenaan keessan milkaa\'e',
      'language_updated': 'Afaan keessan milkaa\'e',
      'currency_updated': 'Qarshii keessan milkaa\'e',
      'expense_added': 'Baa\'insa keessan milkaa\'e',
      'income_added': 'Argama keessan milkaa\'e',
      'transaction_deleted': 'Fe\'aan keessan milkaa\'e',
      'category_added': 'Garee keessan milkaa\'e',
      'category_updated': 'Garee keessan milkaa\'e',
      'category_deleted': 'Garee keessan milkaa\'e',
      'password_changed': 'Jecha Iccitii keessan milkaa\'e',
      'settings_updated': 'Qindaawwan keessan milkaa\'e',
      'changes_saved': 'Jijjirama keessan milkaa\'e',
      'error_occurred': 'Dogoggora Dhufe',
      'try_again_later': 'Mee Booda Irra Deebi\'i',
      'operation_failed': 'Tarkaanfii Hin Milkaane',
      'network_error': 'Dogoggora Internet',
      'server_error': 'Dogoggora Server',
      'validation_error': 'Mee Galchi Keessan Mirkaneessa',
      'required_field': 'Mee Galchi Kana Galchi',
      'invalid_input': 'Galchi Dogoggora',
      'success_message': 'Tarkaanfii Milkaa\'e',

      // Profile Page
      'account_settings': 'Qindaawwan Herregaa',
      'preferences': 'Filatamaa',
      'appearance': 'Mul\'ata',
      'logout_confirmation': 'Ba\'uu Barbaaddanii?',

      // Currency Names
      'currency_birr': 'Birra Itoophiyaa',
      'currency_usd': 'Doolaara Ameerikaa',
      'currency_eur': 'Yuuroo',
      'currency_gbp': 'Paawundii Ingilizii',
      'currency_jpy': 'Yeenaa Jappaanii',
      'currency_inr': 'Ruupii Hindii',
      'currency_cny': 'Yuwaanii Chaayinaa',
      'close': 'Cufi',

      // Edit Profile Dialog
      'image_pick_error': 'Suuraa Filuu Hin Dandeenye',
      'profile_update_error': 'Seenaa Jijjiiruu Dogoggora:',
      'dismiss': 'Cufi',

      // Category Errors
      'category_id_required': 'ID Garee Barbaachisa',
      'category_not_found': 'Garee Hin Argamne',
      'cannot_update_default': 'Garee Default Jijjiiruu Hin Dandeenye',
      'cannot_delete_default': 'Garee Default Haquu Hin Dandeenye',
      'server_failure': 'Dogoggora Server',
      'cache_failure': 'Dogoggora Cache',
      'unexpected_error': 'Dogoggora Hin Eegamne',

      // Category Remote Data Source Errors
      'failed_to_save_category': 'Garee Galchuu Hin Dandeenye',
      'failed_to_get_category': 'Garee Argachuu Hin Dandeenye',
      'failed_to_get_categories': 'Gareewwan Argachuu Hin Dandeenye',
      'failed_to_update_category': 'Garee Jijjiiruu Hin Dandeenye',
      'failed_to_delete_category': 'Garee Haquu Hin Dandeenye',
      'failed_to_get_categories_by_type':
          'Gareewwan Gosaan Argachuu Hin Dandeenye',

      // Add Transaction Page
      'add_transaction': 'Fe\'aa Dabalchi',
      'title': 'Maqaa',
      'enter_amount': 'Lakki Galchi',
      'select_category': 'Garee Filadhu',
      'no_categories': 'Gareewwan Hin Argamne',
      'date': 'Guyyaa',
      'time': 'Sa\'aa',
      'no_description': 'Ibsa Hin Qabne',

      // Edit Transaction Page
      'edit_transaction': 'Fe\'aa Jijjiiruu',
      'update_transaction': 'Fe\'aa Jijjiiruu',
      'delete_transaction': 'Fe\'aa Haquu',
      'delete_transaction_confirmation': 'Fe\'aa Kana Haquu Barbaaddanii?',
      'transaction_update_error': 'Fe\'aa Jijjiiruu Hin Dandeenye',
      'transaction_delete_error': 'Fe\'aa Haquu Hin Dandeenye',
    },
  };
}
